name: Login to Azure
description: Login via Service Principal
inputs:
  client-id:
    required: true
    description: Client (App) Id
  subscription-id:
    required: true
    description: Subscription Id
  tenant-id:
    required: true
    description: Tenant Id

runs:
  using: composite
  steps:
  - name: Log in with Azure
    uses: azure/login@v1
    with:
      # This way the individual secrets are masked in the output if
      # they appear in the workflow logs.
      creds: >
        {
          "clientId":"${{ inputs.client-id }}",
          "subscriptionId":"${{ inputs.subscription-id }}",
          "tenantId":"${{ inputs.tenant-id }}"
        }

  - name: Run az commands
    shell: bash
    run: |
      az account show
