name: Setup Azure BUild Environment
description: Setup azure build environment for podvm image

runs:
  using: composite
  steps:
   - name: Set up Go environment
     uses: actions/setup-go@v2
     with:
       go-version: '1.20'

   - name: Set up GOPATH
     run: |
       echo "export GOPATH=$HOME/go" >> $HOME/.bashrc
       echo "export PATH=$PATH:$GOPATH/bin" >> $HOME/.bashrc
       source $HOME/.bashrc
     shell: bash

   - name: Install Dependencies
     run: |
       rustup target add x86_64-unknown-linux-musl
       sudo apt-get install musl-tools -y
       sudo apt-get install -y libdevmapper-dev
       sudo apt-get install -y libgpgme-dev
       export GOPATH=$HOME/go
     shell: bash
